// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqfluXDMvmjJLiOZefwO-1n_lzVlT-bvE',
    appId: '1:236382410092:web:bdf56fdc618d7c2964cf49',
    messagingSenderId: '236382410092',
    projectId: 'ruh-care-5c901',
    authDomain: 'ruh-care-5c901.firebaseapp.com',
    storageBucket: 'ruh-care-5c901.firebasestorage.app',
    measurementId: 'G-EXPBC6E6MB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1OzZdk-lWyMuCA0dUGMsdIlq_uvGp5yU',
    appId: '1:236382410092:android:da9abf8ada26d0f764cf49',
    messagingSenderId: '236382410092',
    projectId: 'ruh-care-5c901',
    storageBucket: 'ruh-care-5c901.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBDloFo6yx7Q9Db-CINPxN08J0LKmaX5I',
    appId: '1:236382410092:ios:aad0bc043b20dce264cf49',
    messagingSenderId: '236382410092',
    projectId: 'ruh-care-5c901',
    storageBucket: 'ruh-care-5c901.firebasestorage.app',
    iosBundleId: 'com.example.ruhCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBDloFo6yx7Q9Db-CINPxN08J0LKmaX5I',
    appId: '1:236382410092:ios:aad0bc043b20dce264cf49',
    messagingSenderId: '236382410092',
    projectId: 'ruh-care-5c901',
    storageBucket: 'ruh-care-5c901.firebasestorage.app',
    iosBundleId: 'com.example.ruhCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqfluXDMvmjJLiOZefwO-1n_lzVlT-bvE',
    appId: '1:236382410092:web:e1c74d2b0ce64c5264cf49',
    messagingSenderId: '236382410092',
    projectId: 'ruh-care-5c901',
    authDomain: 'ruh-care-5c901.firebaseapp.com',
    storageBucket: 'ruh-care-5c901.firebasestorage.app',
    measurementId: 'G-FV7RQBQ14K',
  );
}
